In [1]:
# Code by Desh Iyer, to display the solutions for the n-queens problem given n as the dimensions of the board and the number of queens.

# Importing libraries
from itertools import permutations
import numpy as np

In [2]:
# Defining a function to implement n-queens
def NQueens(n):
    perm = list(permutations(np.array(range(n))))
    temp = []
    solutions = []

    for i in perm:
        if ((len(set(i-np.array(range(n)))) == n and len(set(i+np.array(range(n)))) == n) == True):
            temp.append(i)

    for i in range(len(temp)):
        board = np.full((n, n), '-')

        for j in range(n):
            board[j][temp[i][j]] = '♕'
            solutions.append(board)

    return solutions


In [3]:
N = 8
solutions = NQueens(N)
print("Total Solutions: ", len(solutions))

for i in solutions:
    print(i)
    print('\n----------------------------------\n')


Total Solutions:  736
[['♕' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '♕' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '♕']
 ['-' '-' '-' '-' '-' '♕' '-' '-']
 ['-' '-' '♕' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '♕' '-']
 ['-' '♕' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '♕' '-' '-' '-' '-']]

----------------------------------

[['♕' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '♕' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '♕']
 ['-' '-' '-' '-' '-' '♕' '-' '-']
 ['-' '-' '♕' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '♕' '-']
 ['-' '♕' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '♕' '-' '-' '-' '-']]

----------------------------------

[['♕' '-' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '♕' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '-' '♕']
 ['-' '-' '-' '-' '-' '♕' '-' '-']
 ['-' '-' '♕' '-' '-' '-' '-' '-']
 ['-' '-' '-' '-' '-' '-' '♕' '-']
 ['-' '♕' '-' '-' '-' '-' '-' '-']
 ['-' '-' '-' '♕' '-' '-' '-' '-']]

----------------------------------

[['♕' '-' '-' '-' '-' '-

In [5]:
n = 4
perm = list(permutations(np.array(range(n))))
temp = []
solutions = []

for i in perm:
    if ((len(set(i-np.array(range(n)))) == n and len(set(i+np.array(range(n)))) == n) == True):
        temp.append(i)

for i in range(len(temp)):
    board = np.full((n, n), '-')

    for j in range(n):
        board[j][temp[i][j]] = '♕'
        solutions.append(board)

In [18]:
solutions

[array([['-', '♕', '-', '-'],
        ['-', '-', '-', '♕'],
        ['♕', '-', '-', '-'],
        ['-', '-', '♕', '-']], dtype='<U1'),
 array([['-', '♕', '-', '-'],
        ['-', '-', '-', '♕'],
        ['♕', '-', '-', '-'],
        ['-', '-', '♕', '-']], dtype='<U1'),
 array([['-', '♕', '-', '-'],
        ['-', '-', '-', '♕'],
        ['♕', '-', '-', '-'],
        ['-', '-', '♕', '-']], dtype='<U1'),
 array([['-', '♕', '-', '-'],
        ['-', '-', '-', '♕'],
        ['♕', '-', '-', '-'],
        ['-', '-', '♕', '-']], dtype='<U1'),
 array([['-', '-', '♕', '-'],
        ['♕', '-', '-', '-'],
        ['-', '-', '-', '♕'],
        ['-', '♕', '-', '-']], dtype='<U1'),
 array([['-', '-', '♕', '-'],
        ['♕', '-', '-', '-'],
        ['-', '-', '-', '♕'],
        ['-', '♕', '-', '-']], dtype='<U1'),
 array([['-', '-', '♕', '-'],
        ['♕', '-', '-', '-'],
        ['-', '-', '-', '♕'],
        ['-', '♕', '-', '-']], dtype='<U1'),
 array([['-', '-', '♕', '-'],
        ['♕', '-', '-', '

In [17]:
board

array([['-', '-', '♕', '-'],
       ['♕', '-', '-', '-'],
       ['-', '-', '-', '♕'],
       ['-', '♕', '-', '-']], dtype='<U1')

In [12]:
np.array(range(n))

array([0, 1, 2, 3])

In [16]:
perm[0]

(0, 1, 2, 3)

In [14]:
perm[0] - np.array(range(n))

array([0, 0, 0, 0])

In [15]:
perm[0] + np.array(range(n))

array([0, 2, 4, 6])

In [8]:
perm

[(0, 1, 2, 3),
 (0, 1, 3, 2),
 (0, 2, 1, 3),
 (0, 2, 3, 1),
 (0, 3, 1, 2),
 (0, 3, 2, 1),
 (1, 0, 2, 3),
 (1, 0, 3, 2),
 (1, 2, 0, 3),
 (1, 2, 3, 0),
 (1, 3, 0, 2),
 (1, 3, 2, 0),
 (2, 0, 1, 3),
 (2, 0, 3, 1),
 (2, 1, 0, 3),
 (2, 1, 3, 0),
 (2, 3, 0, 1),
 (2, 3, 1, 0),
 (3, 0, 1, 2),
 (3, 0, 2, 1),
 (3, 1, 0, 2),
 (3, 1, 2, 0),
 (3, 2, 0, 1),
 (3, 2, 1, 0)]

In [9]:
temp

[(1, 3, 0, 2), (2, 0, 3, 1)]