# Neural Networks - Experiment 1
---
## Objectives
#### Explore the tools with different options like
- Installation
- Tensor creation and deletion
- Tensor manipulation
---

## Installing dependencies

In [9]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\deshi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


## Importing libraries

In [10]:
import numpy as np
import torch

## Tensor (multi-dimensional matrix) operations
[Official Docs](https://pytorch.org/docs/stable/torch.html)

In [11]:
# All elements of the matrix are 0s
torch.zeros(3, 3)

C:\Users\deshi\AppData\Local\Temp\ipykernel_1464\3616952649.py:2: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  torch.zeros(3, 3)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# All elements of the matrix are 1s
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Return a generated sequence taking in step size
torch.arange(0, 100, 5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [14]:
# Evenly splits the range into 'step' parts
torch.linspace(0, 100, 5)

tensor([  0.,  25.,  50.,  75., 100.])

In [15]:
# Fills the array with uninitialized junk values
torch.empty(2, 5)

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39, 1.0378e-38, 9.6429e-39]])

In [16]:
# Tensor filled with random numbers from std normal distribution
torch.randn(100)

tensor([-0.1441,  0.4931,  0.0137,  0.1780, -0.0784,  0.0580,  1.6141, -0.2540,
         0.9326,  0.9732, -0.8747,  1.5478,  0.3667, -1.0240,  0.3575,  1.0673,
         1.0658,  1.0231, -0.4595, -0.9641, -0.1061,  0.3347,  1.4528,  1.4684,
         1.6532,  0.1425,  1.3478, -1.3161,  1.6304,  0.2816, -1.2346,  0.3824,
        -2.2219,  2.6061, -0.1366, -0.8252,  1.2990, -1.2658,  0.4100,  0.1592,
         0.4771,  0.5210, -0.8022,  0.1468, -1.6688, -0.0116, -0.0321, -0.7173,
        -0.9326,  0.7478, -0.8739, -1.9487, -0.3818,  0.2339,  0.8176, -0.0099,
         0.7126,  0.5009,  0.8836, -1.6556,  0.7059,  0.2416, -0.7503,  0.3917,
         1.3780,  0.9809,  0.7447, -0.1924,  0.8000, -1.1070, -1.5040,  0.8779,
        -0.3070, -0.1204,  0.0934, -0.4856, -0.7082, -0.2100,  0.9678, -0.1014,
        -0.2761,  0.4881, -1.5508, -0.5583,  0.2347,  0.4122,  2.3718, -0.0506,
        -0.1292, -0.6767,  0.6320, -1.4318,  0.4073,  0.7545,  1.3772,  0.3973,
         0.4984,  2.0322,  0.2174, -0.91

In [17]:
m = torch.randn(4, 5)
print(m, '\n\nShape:', m.shape)

tensor([[ 0.2572, -0.2351, -0.1496,  1.5702, -0.1826],
        [ 0.1651, -1.2118,  1.5379, -0.1156,  1.0233],
        [ 0.9182,  0.6025, -0.0694,  0.1663, -0.0701],
        [-0.0834, -0.9638, -0.1343, -0.3478,  0.2926]]) 

Shape: torch.Size([4, 5])


In [ ]:
# Creating a diagonal matrix with dimension as argument
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
# Create a tensor of inputted dimensions with a range between 0 and 1 distributed uniformly
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.9321, 0.9245, 0.7897],
        [0.4073, 0.6365, 0.7247],
        [0.9422, 0.0970, 0.5028]])

In [24]:
# Delete a tensor previously created
del a

## Tensor manipulation

### Concatenation of two tensors

In [ ]:
T1 = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

T2 = torch.tensor(
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
)

torch.cat((T1, T2), dim=0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

### Unbinding of a tensor into two tensors

In [ ]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

torch.unbind(a, dim=0)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

### Working with complex and polar tensors

In [ ]:
# Working with complex numbers
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)

print(z, z.dtype, sep='\n')

tensor([1.+3.j, 2.+4.j])
torch.complex64


In [ ]:
# Create initial tensor
abs = torch.tensor([1, 2], dtype=torch.float64)

# Creating angle tensor
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)

# out = abs⋅cos(angle) + abs⋅sin(angle) ⋅ j
z = torch.polar(abs, angle)
z

# Note: Tensors are required to be float since polar does not take long/double input

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

### Changing the dimensions using permutations

In [ ]:
x = torch.randn(2, 3, 5)
print(x, x.size(), sep='\n\n')

tensor([[[ 0.0021,  0.8766, -0.7802, -0.2591, -0.2573],
         [ 0.2976,  0.7922, -0.3852, -0.9810, -0.0581],
         [ 0.6139,  1.7068,  0.4340,  0.5337, -0.3592]],

        [[ 1.3242,  1.1937, -1.2252,  1.5723,  1.1369],
         [-0.4887,  0.2416,  0.1550, -0.2451,  0.0667],
         [ 0.6897,  0.3954,  1.5126, -1.8175,  0.1613]]])

torch.Size([2, 3, 5])


In [ ]:
torch.permute(x, (2, 0, 1))

tensor([[[ 0.0021,  0.2976,  0.6139],
         [ 1.3242, -0.4887,  0.6897]],

        [[ 0.8766,  0.7922,  1.7068],
         [ 1.1937,  0.2416,  0.3954]],

        [[-0.7802, -0.3852,  0.4340],
         [-1.2252,  0.1550,  1.5126]],

        [[-0.2591, -0.9810,  0.5337],
         [ 1.5723, -0.2451, -1.8175]],

        [[-0.2573, -0.0581, -0.3592],
         [ 1.1369,  0.0667,  0.1613]]])

In [ ]:
x = torch.randn(2, 5)
x

tensor([[-0.2062, -0.0284,  1.5630,  0.7954,  1.5845],
        [ 1.5999, -2.2548,  1.1825, -0.8476,  0.0107]])

In [ ]:
transpose = x.t()

In [ ]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[-0.2062, -0.0284,  1.5630,  0.7954,  1.5845],
        [ 1.5999, -2.2548,  1.1825, -0.8476,  0.0107]])
torch.Size([2, 5])

Transposed tensor:
tensor([[-0.2062,  1.5999],
        [-0.0284, -2.2548],
        [ 1.5630,  1.1825],
        [ 0.7954, -0.8476],
        [ 1.5845,  0.0107]])
torch.Size([5, 2])


### Transpose with 3 dimensional tensors

In [ ]:
x = torch.randn(2, 3, 5)

In [ ]:
transpose = torch.transpose(x, 0, 2)
# transpose = torch.transpose(x, -1, 2)

In [ ]:
# Updated shapes
print(x.shape, transpose.shape, sep='\n')

torch.Size([2, 3, 5])
torch.Size([5, 3, 2])


In [ ]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[[-0.0273, -0.3957,  0.6319, -0.5524, -0.4849],
         [-0.2877,  0.3376, -0.0850, -0.8156, -0.1943],
         [-1.1009, -0.8948,  0.5928,  0.1279, -0.3758]],

        [[ 0.5721,  0.1380, -1.1639, -0.1852, -0.3920],
         [-0.8322,  0.1930,  0.6484, -0.1677, -0.5259],
         [-0.2164, -1.6437,  1.3361,  0.7160, -0.6279]]])
torch.Size([2, 3, 5])

Transposed tensor:
tensor([[[-0.0273,  0.5721],
         [-0.2877, -0.8322],
         [-1.1009, -0.2164]],

        [[-0.3957,  0.1380],
         [ 0.3376,  0.1930],
         [-0.8948, -1.6437]],

        [[ 0.6319, -1.1639],
         [-0.0850,  0.6484],
         [ 0.5928,  1.3361]],

        [[-0.5524, -0.1852],
         [-0.8156, -0.1677],
         [ 0.1279,  0.7160]],

        [[-0.4849, -0.3920],
         [-0.1943, -0.5259],
         [-0.3758, -0.6279]]])
torch.Size([5, 3, 2])


___
## References
1. https://pytorch.org/docs/stable/tensors.html#torch.Tensor
2. https://dev.to/balapriya/useful-tensor-manipulation-functions-in-pytorch-4g4c