## Installing dependency

In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


## Importing library

In [2]:
import numpy as np
import torch

## Tensor (multi-dimensional matrix) operations
[Official Docs](https://pytorch.org/docs/stable/torch.html)

In [3]:
# All elements of the matrix are 0s
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# All elements of the matrix are 1s
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
# Return a generated sequence taking in step size
torch.arange(0, 100, 5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [6]:
# Evenly splits the range into 'step' parts
torch.linspace(0, 100, 5)

tensor([  0.,  25.,  50.,  75., 100.])

In [7]:
# Fills the array with uninitialized junk values
torch.empty(2, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
# Tensor filled with random numbers from std normal distribution
torch.randn(100)

tensor([-0.1761,  0.4264, -0.5234, -0.7991,  0.1697,  0.3013, -0.6513, -0.0155,
         0.4691,  2.3918,  0.0892,  0.3067,  1.6476, -0.2836, -0.4693, -0.0443,
        -0.2166, -1.1753,  0.5210,  1.0145, -0.7908, -1.1932, -0.1147,  0.0948,
         0.9060,  0.2691, -0.2881, -0.1211,  0.4187, -0.9039, -1.0561, -0.1452,
        -2.7968, -0.7762,  1.8044,  0.7840,  1.8438, -1.1530, -1.1769,  0.3485,
        -1.0314, -0.6899, -0.6418, -0.7536, -1.1358,  0.6572, -0.5576,  0.2138,
         2.3914, -0.6485, -2.0754, -0.1190,  0.1363, -1.0390,  2.3835,  0.8431,
        -0.3578,  0.2869,  0.8991,  0.3630, -2.6876, -0.5239,  1.2665, -0.8899,
        -1.3211,  0.4772, -1.8095,  1.4289,  0.8889,  0.7524,  0.0173, -0.2507,
         0.0895, -0.2275, -1.5944, -0.9221, -1.2665, -1.0646, -1.2795, -2.6949,
        -0.5167, -0.1965, -0.6749, -0.0473, -0.2981,  1.7424,  0.4783,  0.2253,
         1.8852,  0.9212,  0.9651,  0.5852,  0.8271, -1.7630,  0.0785,  0.6675,
         0.3469,  1.0445, -0.7715,  1.53

In [9]:
m = torch.randn(4, 5)
print(m, '\n\nShape:', m.shape)

tensor([[-0.4407, -0.2326, -0.7568,  0.3849,  0.4791],
        [ 0.0607,  0.0535,  0.2957,  1.4829, -0.4789],
        [ 0.4685, -0.2522, -0.6476, -0.2932, -1.4677],
        [ 0.8195,  0.8906, -1.9078, -1.1206, -0.1353]]) 

Shape: torch.Size([4, 5])


In [10]:
# Convert numpy array to tensor
a = np.array(
    [1, 2, 3]
)
a
b = torch.from_numpy(a)
b

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
# Creating a diagonal matrix with dimension as argument
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Tensor manipulation

In [12]:
# Working with complex numbers
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)

print(z, z.dtype, sep='\n')

tensor([1.+3.j, 2.+4.j])
torch.complex64


In [13]:
# Create initial tensor
abs = torch.tensor([1, 2], dtype=torch.float64)

# Creating angle tensor
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)

# out = abs⋅cos(angle) + abs⋅sin(angle) ⋅ j
z = torch.polar(abs, angle)
z

# Note: Tensors are required to be float since polar does not take long/double input

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

## Changing the dimensions using permutations

In [14]:
x = torch.randn(2, 3, 5)
print(x, x.size(), sep='\n\n')

tensor([[[ 0.5031,  1.0244,  0.2883,  0.1561, -1.4250],
         [-1.4547,  1.2780, -0.9809,  1.5264, -1.0575],
         [-0.0635, -0.5602,  0.7873,  0.2938,  0.4340]],

        [[ 0.8156,  0.1266,  1.5631, -1.8182,  0.1202],
         [ 0.2356, -0.3723,  0.8180,  0.9200, -1.3348],
         [-0.1761, -0.3277,  1.1077,  0.9028,  0.4097]]])

torch.Size([2, 3, 5])


In [15]:
torch.permute(x, (2, 0, 1))

tensor([[[ 0.5031, -1.4547, -0.0635],
         [ 0.8156,  0.2356, -0.1761]],

        [[ 1.0244,  1.2780, -0.5602],
         [ 0.1266, -0.3723, -0.3277]],

        [[ 0.2883, -0.9809,  0.7873],
         [ 1.5631,  0.8180,  1.1077]],

        [[ 0.1561,  1.5264,  0.2938],
         [-1.8182,  0.9200,  0.9028]],

        [[-1.4250, -1.0575,  0.4340],
         [ 0.1202, -1.3348,  0.4097]]])

In [16]:
x = torch.randn(2, 5)
x

tensor([[-0.1640, -1.8198,  1.6562, -1.5932, -0.2742],
        [-1.3684,  0.4973, -0.6079,  1.0625,  0.3146]])

In [17]:
transpose = x.t()

In [18]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[-0.1640, -1.8198,  1.6562, -1.5932, -0.2742],
        [-1.3684,  0.4973, -0.6079,  1.0625,  0.3146]])
torch.Size([2, 5])

Transposed tensor:
tensor([[-0.1640, -1.3684],
        [-1.8198,  0.4973],
        [ 1.6562, -0.6079],
        [-1.5932,  1.0625],
        [-0.2742,  0.3146]])
torch.Size([5, 2])


## Transpose with 3 dimensional tensors

In [19]:
x = torch.randn(2, 3, 5)

In [20]:
transpose = torch.transpose(x, 0, 2)
# transpose = torch.transpose(x, -1, 2)

In [21]:
# Updated shapes
print(x.shape, transpose.shape, sep='\n')

torch.Size([2, 3, 5])
torch.Size([5, 3, 2])


In [22]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[[ 1.5083, -0.6501, -0.9240, -0.7150,  0.1747],
         [ 0.5238, -0.0807,  1.6389,  0.5889,  1.0357],
         [ 0.7930, -2.0331,  1.2977, -1.7428, -0.2422]],

        [[ 0.7218, -1.6971,  1.1330, -1.0758,  0.0098],
         [ 1.2187, -0.0834, -0.0467, -0.8476, -1.1706],
         [-0.0552,  1.5400,  1.9600,  1.6548, -1.8948]]])
torch.Size([2, 3, 5])

Transposed tensor:
tensor([[[ 1.5083,  0.7218],
         [ 0.5238,  1.2187],
         [ 0.7930, -0.0552]],

        [[-0.6501, -1.6971],
         [-0.0807, -0.0834],
         [-2.0331,  1.5400]],

        [[-0.9240,  1.1330],
         [ 1.6389, -0.0467],
         [ 1.2977,  1.9600]],

        [[-0.7150, -1.0758],
         [ 0.5889, -0.8476],
         [-1.7428,  1.6548]],

        [[ 0.1747,  0.0098],
         [ 1.0357, -1.1706],
         [-0.2422, -1.8948]]])
torch.Size([5, 3, 2])
