## Importing library

In [1]:
import numpy as np
import torch

## Tensor (multi-dimensional matrix) operations
[Official Docs](https://pytorch.org/docs/stable/torch.html)

In [2]:
# All elements of the matrix are 0s
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# All elements of the matrix are 1s
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
# Return a generated sequence taking in step size
torch.arange(0, 100, 5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [5]:
# Evenly splits the range into 'step' parts
torch.linspace(0, 100, 5)

tensor([  0.,  25.,  50.,  75., 100.])

In [6]:
# Fills the array with uninitialized junk values
torch.empty(2, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
# Tensor filled with random numbers from std normal distribution
torch.randn(100)

tensor([ 1.5647, -0.4814,  0.3663, -0.0827,  0.4506, -0.0100,  0.2208,  0.4380,
        -0.8832,  1.9941, -0.4689, -0.5195, -1.6247, -0.5719,  1.2447, -1.2387,
         0.4997, -0.8289,  0.9411, -1.6943, -1.3683,  1.0729,  0.4659, -0.1005,
        -0.3868,  1.4872,  1.0048, -0.6178,  0.6936,  0.6510, -1.1507,  0.0083,
        -0.1438,  0.6819,  1.0505, -1.7031, -0.7201, -0.4874,  0.6360,  0.0680,
         1.2025, -0.5299, -0.2822,  0.3232,  2.4200, -0.0880,  0.7375, -2.0175,
        -0.2909,  0.8216, -0.7349, -1.1144, -0.5321, -0.5616, -0.7055, -0.0103,
         0.6935,  0.4273,  0.9936,  1.9380, -0.8602, -0.4562, -0.4275, -0.6889,
        -0.5076,  0.1171,  0.0478, -0.2138, -1.3140, -0.7005,  0.3728, -0.3876,
        -0.9480,  0.0688,  1.5200, -0.5160, -2.6326, -0.2838, -1.4248,  1.7629,
         2.5221,  0.0701, -0.9938,  0.0263,  0.5501, -0.6058,  0.1307,  0.1900,
        -0.7646,  0.1090, -1.6075, -0.1580,  0.6117, -0.0216,  0.4558, -1.7660,
         1.1205, -0.7137, -0.4524, -0.59

In [8]:
m = torch.randn(4, 5)
print(m, '\n\nShape:', m.shape)

tensor([[ 0.2636,  1.1678, -1.7163,  0.4773, -0.7164],
        [ 0.1397, -2.1117, -1.6054, -0.0139, -0.0058],
        [ 0.3316,  0.8241, -0.5208, -0.0857, -0.9031],
        [-0.9871,  1.4010,  0.7044, -0.1591,  0.8179]]) 

Shape: torch.Size([4, 5])


In [9]:
# Convert numpy array to tensor
a = np.array(
    [1, 2, 3]
)
a

b = torch.from_numpy(a)
b

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
# Creating a diagonal matrix with dimension as argument
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Tensor manipulation

In [11]:
# Working with complex numbers
real = torch.tensor([1, 2], dtype=torch.float32)
imag = torch.tensor([3, 4], dtype=torch.float32)
z = torch.complex(real, imag)

print(z, z.dtype, sep='\n')

tensor([1.+3.j, 2.+4.j])
torch.complex64


In [12]:
# Create initial tensor
abs = torch.tensor([1, 2], dtype=torch.float64)

# Creating angle tensor
angle = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)

# out = abs⋅cos(angle) + abs⋅sin(angle) ⋅ j
z = torch.polar(abs, angle)
z

# Note: Tensors are required to be float since polar does not take long/double input

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

## Changing the dimensions using permutations

In [13]:
x = torch.randn(2, 3, 5)
print(x, x.size(), sep='\n\n')

tensor([[[ 0.0021,  0.8766, -0.7802, -0.2591, -0.2573],
         [ 0.2976,  0.7922, -0.3852, -0.9810, -0.0581],
         [ 0.6139,  1.7068,  0.4340,  0.5337, -0.3592]],

        [[ 1.3242,  1.1937, -1.2252,  1.5723,  1.1369],
         [-0.4887,  0.2416,  0.1550, -0.2451,  0.0667],
         [ 0.6897,  0.3954,  1.5126, -1.8175,  0.1613]]])

torch.Size([2, 3, 5])


In [14]:
torch.permute(x, (2, 0, 1))

tensor([[[ 0.0021,  0.2976,  0.6139],
         [ 1.3242, -0.4887,  0.6897]],

        [[ 0.8766,  0.7922,  1.7068],
         [ 1.1937,  0.2416,  0.3954]],

        [[-0.7802, -0.3852,  0.4340],
         [-1.2252,  0.1550,  1.5126]],

        [[-0.2591, -0.9810,  0.5337],
         [ 1.5723, -0.2451, -1.8175]],

        [[-0.2573, -0.0581, -0.3592],
         [ 1.1369,  0.0667,  0.1613]]])

In [15]:
x = torch.randn(2, 5)
x

tensor([[-0.2062, -0.0284,  1.5630,  0.7954,  1.5845],
        [ 1.5999, -2.2548,  1.1825, -0.8476,  0.0107]])

In [16]:
transpose = x.t()

In [17]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[-0.2062, -0.0284,  1.5630,  0.7954,  1.5845],
        [ 1.5999, -2.2548,  1.1825, -0.8476,  0.0107]])
torch.Size([2, 5])

Transposed tensor:
tensor([[-0.2062,  1.5999],
        [-0.0284, -2.2548],
        [ 1.5630,  1.1825],
        [ 0.7954, -0.8476],
        [ 1.5845,  0.0107]])
torch.Size([5, 2])


## Transpose with 3 dimensional tensors

In [18]:
x = torch.randn(2, 3, 5)

In [19]:
transpose = torch.transpose(x, 0, 2)
# transpose = torch.transpose(x, -1, 2)

In [20]:
# Updated shapes
print(x.shape, transpose.shape, sep='\n')

torch.Size([2, 3, 5])
torch.Size([5, 3, 2])


In [21]:
print('Original tensor:', x, x.shape, '\nTransposed tensor:', transpose, transpose.shape, sep='\n')

Original tensor:
tensor([[[-0.0273, -0.3957,  0.6319, -0.5524, -0.4849],
         [-0.2877,  0.3376, -0.0850, -0.8156, -0.1943],
         [-1.1009, -0.8948,  0.5928,  0.1279, -0.3758]],

        [[ 0.5721,  0.1380, -1.1639, -0.1852, -0.3920],
         [-0.8322,  0.1930,  0.6484, -0.1677, -0.5259],
         [-0.2164, -1.6437,  1.3361,  0.7160, -0.6279]]])
torch.Size([2, 3, 5])

Transposed tensor:
tensor([[[-0.0273,  0.5721],
         [-0.2877, -0.8322],
         [-1.1009, -0.2164]],

        [[-0.3957,  0.1380],
         [ 0.3376,  0.1930],
         [-0.8948, -1.6437]],

        [[ 0.6319, -1.1639],
         [-0.0850,  0.6484],
         [ 0.5928,  1.3361]],

        [[-0.5524, -0.1852],
         [-0.8156, -0.1677],
         [ 0.1279,  0.7160]],

        [[-0.4849, -0.3920],
         [-0.1943, -0.5259],
         [-0.3758, -0.6279]]])
torch.Size([5, 3, 2])
